[package]
name = "rustywind"
version = "0.6.7"
authors = ["Praveen Perera <praveen@avencera.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4"
regex = "1"
lazy_static = "1.4.0"
itertools = "0.9"
indoc = "1.0"
clap = "2.33"
rayon = "1.4"

#async
futures = "0.3"
async-std = {version = "1.6", features = ["attributes"]}


[dev-dependencies]
pretty_assertions = "0.6"
